### ISSUE TITLE
Add cloudwatch agent to images.

### ISSUE THREAD

**Issue by trevars** [uc-cdis/images#13]
@philloooo commented on [Wed Mar 29 2017](https://github.com/uc-cdis/cloud-automation/issues/1)

---

@philloooo commented on [Fri Jul 14 2017](https://github.com/uc-cdis/cloud-automation/issues/1#issuecomment-315392473)

Send notice when a superuser logs in

---

@trevars commented on [Mon Jul 17 2017](https://github.com/uc-cdis/cloud-automation/issues/1#issuecomment-315843346)

Not added to image. Need to add agent to packer image.

**Comment by trevars** [comment]
This task is to add the cloudwatch agent to logging image and squid image.

**Comment by zflamig** [comment]
We want to be able to log successful and unsuccessful sign ins at the very least.

**Comment by fauzigo** [comment]
Agent has been added and tested.

Branch feat/cloudwatch contains changes made to the packer files so the new image (1.0.2) are deployed ready to start sending /var/log/auth.log to cloudwatch.

If we wanted to add more logs by default to all images we may need to edit configs/awslogs.conf respectively.
